package com.max.security.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.max.security.greendao.FileModels;

import com.max.security.greendao.FileModelsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fileModelsDaoConfig;

    private final FileModelsDao fileModelsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fileModelsDaoConfig = daoConfigMap.get(FileModelsDao.class).clone();
        fileModelsDaoConfig.initIdentityScope(type);

        fileModelsDao = new FileModelsDao(fileModelsDaoConfig, this);

        registerDao(FileModels.class, fileModelsDao);
    }
    
    public void clear() {
        fileModelsDaoConfig.getIdentityScope().clear();
    }

    public FileModelsDao getFileModelsDao() {
        return fileModelsDao;
    }

}
