package com.max.security.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FILE_MODELS.
 */
public class FileModels {

    /** Not-null value. */
    private String Id;
    /** Not-null value. */
    private String FileName;
    /** Not-null value. */
    private String FilePath;
    /** Not-null value. */
    private String OriginPath;
    private int FileType;

    public FileModels() {
    }

    public FileModels(String Id) {
        this.Id = Id;
    }

    public FileModels(String Id, String FileName, String FilePath, String OriginPath, int FileType) {
        this.Id = Id;
        this.FileName = FileName;
        this.FilePath = FilePath;
        this.OriginPath = OriginPath;
        this.FileType = FileType;
    }

    /** Not-null value. */
    public String getId() {
        return Id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String Id) {
        this.Id = Id;
    }

    /** Not-null value. */
    public String getFileName() {
        return FileName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFileName(String FileName) {
        this.FileName = FileName;
    }

    /** Not-null value. */
    public String getFilePath() {
        return FilePath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFilePath(String FilePath) {
        this.FilePath = FilePath;
    }

    /** Not-null value. */
    public String getOriginPath() {
        return OriginPath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOriginPath(String OriginPath) {
        this.OriginPath = OriginPath;
    }

    public int getFileType() {
        return FileType;
    }

    public void setFileType(int FileType) {
        this.FileType = FileType;
    }

}
